name: Deploy Coffee Ta Cocktails to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3985BD64C8A147F08F088FBA960FDCEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADA4864553A2407CAAEED55DA50BBC49 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D2B87176B44741BCA189C813DF01DB52 }}

      - name: Deploy static website to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: coffee-ta-cocktails
          slot-name: Production
          package: .
